#lang sicp

(define (make-deque-item item)
    (cons item (cons '() '())))
(define (deque-item-next item)
    (cddr item))
(define (deque-item-prev item)
    (cadr item))
(define (deque-item-item item)
    (car item))
(define (set-deque-item-next! item next)
    (set-cdr! (cdr item) next))
(define (set-deque-item-prev! item prev)
    (set-car! (cdr item) prev))

(define (front-ptr deque)
    (car deque))
(define (rear-ptr deque)
    (cdr deque))
(define (set-front-ptr! deque item)
    (set-car! deque item))
(define (set-rear-ptr! deque item)
    (set-cdr! deque item))

(define (make-deque)
    (cons '() '()))
(define (empty-deque? deque)
    (or (null? (front-ptr deque))
        (null? (rear-ptr deque))))
(define (front-deque deque)
    (if (empty-deque? deque)
        (error "Empty deque from front" deque)
        (deque-item-item (front-ptr deque))))
(define (rear-deque deque)
    (if (empty-deque? deque)
        (error "Empty deque from rear" deque)
        (deque-item-item (rear-ptr deque))))
(define (front-insert-deque! deque item)
    (let ((deque-item (make-deque-item item)))
        (if (empty-deque? deque)
            (begin
                (set-front-ptr! deque deque-item)
                (set-rear-ptr! deque deque-item)
                deque)
            (begin
                (set-deque-item-prev! (front-ptr deque) deque-item)
                (set-deque-item-next! deque-item (front-ptr deque))
                (set-front-ptr! deque deque-item)
                deque))))
(define (rear-insert-deque! deque item)
    (let ((deque-item (make-deque-item item)))
        (if (empty-deque? deque)
            (begin
                (set-front-ptr! deque deque-item)
                (set-rear-ptr! deque deque-item)
                deque)
            (begin
                (set-deque-item-next! (rear-ptr deque) deque-item)
                (set-deque-item-prev! deque-item (rear-ptr deque))
                (set-rear-ptr! deque deque-item)
                deque))))
(define (front-delete-deque! deque)
    (if (empty-deque? deque)
        (error "Empty deque from front" deque)
        (begin
            (set-front-ptr! deque (deque-item-next (front-ptr deque)))
            (if (empty-deque? deque)
                0
                (set-deque-item-prev! (front-ptr deque) '()))
            deque)))
(define (rear-delete-deque! deque)
    (if (empty-deque? deque)
        (error "Empty deque from rear" deque)
        (begin
            (set-rear-ptr! deque (deque-item-prev (rear-ptr deque)))
            (if (empty-deque? deque)
                0
                (set-deque-item-next! (rear-ptr deque) '()))
            deque)))

(define (print-deque deque)
    (define (iter item)
        (display (deque-item-item item))
        (if (null? (deque-item-next item))
            (display ")")
            (begin
                (display " ")
                (iter (deque-item-next item)))))
    (newline)
    (display "(")
    (if (empty-deque? deque)
        (display ")")
        (iter (front-ptr deque)))
    (newline))

(define q (make-deque))
(rear-insert-deque! q 'a)
(front-insert-deque! q 'b)
(rear-insert-deque! q 'c)
(rear-insert-deque! q 'd)
(print-deque q)
(rear-delete-deque! q)
(front-delete-deque! q)
(print-deque q)
(rear-delete-deque! q)
(front-delete-deque! q)
(front-delete-deque! q)
(print-deque q)
;(rear-delete-deque! q)
;(rear-delete-deque! q)