#lang sicp

(define (make-queue)
    (let ((front-ptr '())
            (rear-ptr '()))
        (define (empty-queue?)
            (null? front-ptr))
        (define (front-queue)
            (if (empty-queue?)
                (error "Empty queue")
                (car front-ptr)))
        (define (insert-queue! item)
            (let ((queue-item (cons item '())))
                (if (empty-queue?)
                    (begin
                        (set! front-ptr queue-item)
                        (set! rear-ptr queue-item))
                    (begin
                        (set-cdr! rear-ptr queue-item)
                        (set! rear-ptr queue-item)))))
        (define (delete-queue!)
            (if (empty-queue?)
                (error "Empty queue")
                (begin
                    (set! front-ptr (cdr front-ptr)))))
        (define (print-queue)
            front-ptr)
        (define (dispatch m)
            (cond ((eq? m 'front-queue)
                    front-queue)
                ((eq? m 'empty-queue?)
                    empty-queue?)
                ((eq? m 'insert-queue!)
                    insert-queue!)
                ((eq? m 'delete-queue!)
                    delete-queue!)
                ((eq? m 'print-queue)
                    print-queue)))
        dispatch))

(define (empty-queue? queue)
    ((queue 'empty-queue?)))
(define (front-queue queue)
    ((queue 'front-queue)))
(define (insert-queue! queue item)
    ((queue 'insert-queue!) item))
(define (delete-queue! queue)
    ((queue 'delete-queue!)))
(define (print-queue queue)
    ((queue 'print-queue)))

; tests
(define q1 (make-queue))
(insert-queue! q1 'a)
(insert-queue! q1 'b)
(delete-queue! q1)
;(delete-queue! q1)

(print-queue q1)