#lang sicp

(define (adder a1 a2 sum)
    (define (proc)
        (cond
            ((and (has-value? a1)
                    (has-value? a2))
                (set-value! sum
                    (+ (get-value a1) (get-value a2))
                    me))
            ((and (has-value? a1)
                    (has-value? sum))
                (set-value! a2
                    (- (get-value sum) (get-value a1))
                    me))
            ((and (has-value? a2)
                    (has-value? sum))
                (set-value! a1
                    (- (get-value sum) (get-value a2))
                    me))))
    (define (forget-proc)
        (forget-value! a1)
        (forget-value! a2)
        (forget-value! sum)
        (proc))
    (define (me m)
        (cond
            ((eq? m 'value-set) proc)
            ((eq? m 'value-forget) forget-proc)
            (else (error "Invalid operation: ADDER" m))))
    (connect a1 me)
    (connect a2 me)
    (connect sum me)
    me)

(define (multiplier m1 m2 product)
    (define (proc)
        (cond
            ((or (and (has-value? m1) (= (get-value m1) 0))
                (and (has-value? m2) (= (get-value m2) 0)))
                (set-value! product 0 me))
            ((and (has-value? m1) (has-value? m2))
                (set-value! product
                    (* (get-value m1) (get-value m2))
                    me))
            ((and (has-value? m1) (has-value? product))
                (set-value! m2
                    (/ (get-value product) (get-value m1))
                    me))
            ((and (has-value? m2) (has-value? product))
                (set-value! m1
                    (/ (get-value product) (get-value m2))
                    me))))
    (define (forget-proc)
        (forget-value! m1)
        (forget-value! m2)
        (forget-value! product)
        (proc))
    (define (me m)
        (cond
            ((eq? m 'value-set) proc)
            ((eq? m 'value-forget) forget-proc)
            (else (error "Invalid operation: MULTIPLIER" m))))
    (connect m1 me)
    (connect m2 me)
    (connect product me)
    me)

(define (constant c x)
    (define (me m)
        (error "Invalid operation: CONSTANT" m))
    (connect x me)
    (set-value! x c me)
    me)

(define (inform-about-value constraint)
    ((constraint 'value-set)))
(define (inform-about-no-value constraint)
    ((constraint 'value-forget)))

(define (make-connector)
    (let ((value false)
            (informant false)
            (constraints '()))
        (define (set-value-proc! new-value setter)
            (cond
                ((not (has-value? me))
                    (set! value new-value)
                    (set! informant setter)
                    (for-each-except setter
                        inform-about-value
                        constraints))
                ((not (= value new-value))
                    (error "Contradiction" (list value new-value)))))
        (define (forget-value-proc! retractor)
            (if (eq? retractor informant)
                (begin (set! informant false)
                    (for-each-except retractor
                        inform-about-no-value
                        constraints))))
        (define (connect-proc! new-constraint)
            (if (not (memq new-constraint constraints))
                (set! constraints
                    (cons new-constraint constraints)))
            (if (has-value? me)
                (inform-about-value new-constraint)))
        (define (me m)
            (cond
                ((eq? m 'has-value?)
                    (if informant true false))
                ((eq? m 'get-value) value)
                ((eq? m 'set-value!) set-value-proc!)
                ((eq? m 'forget-value!) forget-value-proc!)
                ((eq? m 'connect!) connect-proc!)
                (else (error "Invalid operation: MAKE-CONNECTOR" m))))
        me))

(define (has-value? connector)
    (connector 'has-value?))
(define (get-value connector)
    (connector 'get-value))
(define (set-value! connector value setter)
    ((connector 'set-value!) value setter))
(define (forget-value! connector retractor)
    ((connector 'forget-value!) retractor))
(define (connect connector constraint)
    ((connector 'connect!) constraint))

(define (probe name connector)
    (define (print-probe value)
        (newline) (display "Probe: ") (display name)
        (display " = ") (display value))
    (define (process-new-value)
        (print-probe (get-value connector)))
    (define (process-forget-value)
        (print-probe "?"))
    (define (me m)
        (cond
            ((eq? m 'value-set) process-new-value)
            ((eq? m 'value-forget) process-forget-value)
            (else (error "Invalid operation: PROBE" m))))
    (connect connector me)
    me)

(define (for-each-except except proc list)
    (define (loop sublist)
        (if (not (null? sublist))
            (if (eq? (car sublist) except)
                (loop (cdr sublist))
                (begin (proc (car sublist))
                    (loop (cdr sublist))))))
    (loop list))


; test
(define (averager a b c)
    (let ((lc1 (make-connector))
            (lc2 (make-connector)))
        (constant 2 lc1)
        (multiplier lc1 c lc2)
        (adder a b lc2)))

(define C (make-connector))
(define A (make-connector))
(define B (make-connector))

(probe 'A A)
(probe 'B B)
(probe 'C C)
(averager A B C)

(set-value! C 1 'user)
(set-value! A 0 'user)

; 3.34 - if 'user set b, a will not be computed

; 3.35
(define (squarer a b)
    (define (square x)
        (* x x))
    (define (process-new-value)
        (if (has-value? b)
            (if (< (get-value b) 0)
                (error "square less than 0: SQUARER" (get-value b))
                (set-value! a
                    (sqrt (get-value b))
                    me))
            (if (has-value? a)
                (set-value! b (square (get-value a)) me))))
    (define (process-forget-value)
        (forget-value! a)
        (forget-value! b)
        (process-new-value))
    (define (me m)
        (cond
            ((eq? m 'value-set) process-new-value)
            ((eq? m 'value-forget) process-forget-value)
            (else (error "Invalid operation: SQUARER" m))))
    (connect a me)
    (connect b me)
    me)

(define squarer-a (make-connector))
(define squarer-b (make-connector))
(probe 'squarer-a squarer-a)
(probe 'squarer-b squarer-b)
(squarer squarer-a squarer-b)
(set-value! squarer-b 2 'user)

; 3.37
;(define C (make-connector))
;(define F (make-connector))
; (define (celsius-fahrenheit-converter c f)
;     (let ((lc1 (make-connector))
;             (lc2 (make-connector))
;             (lc3 (make-connector))
;             (lc4 (make-connector))
;             (lc5 (make-connector)))
;         (multiplier c lc1 lc2)
;         (multiplier lc3 lc4 lc2)
;         (adder lc3 lc5 f)
;         (constant 9 lc1)
;         (constant 5 lc4)
;         (constant 32 lc5)))
(define (c+ x y)
    (let ((z (make-connector)))
        (adder x y z)
        z))
(define (c* x y)
    (let ((z (make-connector)))
        (multiplier x y z)
        z))
(define (c/ x y)
    (let ((z (make-connector)))
        (multiplier z y x)
        z))
(define (cv x)
    (let ((z (make-connector)))
        (constant x z)
        z))
(define (celsius-fahrenheit-converter x)
    (c+ (c* (c/ (cv 9) (cv 5))
            x)
        (cv 32)))
(define celsius (make-connector))
(define fahrenheit (celsius-fahrenheit-converter celsius))
(probe 'celsius celsius)
(probe 'fahrenheit fahrenheit)
(set-value! celsius 10 'user)