#lang sicp

(define (make-account balance password)
    (define perm-error-count 0)
    (define (withdraw amount)
        (if (>= balance amount)
            (begin (set! balance (- balance amount))
                balance)
            "Insufficient funds"))
    (define (deposit amount)
        (begin (set! balance (+ balance amount))
            balance))
    (define (call-the-cops)
        "Police is comming!")
    (define (perm-error amount)
        (if (> perm-error-count 7) (call-the-cops)
            (begin (set! perm-error-count (+ perm-error-count 1))
                "Incorrect password")))
    (define (dispatch pass act)
        (cond 
            ((not (eq? pass password)) perm-error)
            ((eq? act 'withdraw) withdraw)
            ((eq? act 'deposit) deposit)
            (else (error "Unknown request: MAKE-ACCOUNT" act))))
    dispatch)

(define acc (make-account 100 'secret-password))

((acc 'secret-password 'withdraw) 40)
((acc 'some-other-password 'deposit) 50)
((acc 'some-other-password 'deposit) 50)
((acc 'some-other-password 'deposit) 50)
((acc 'some-other-password 'deposit) 50)
((acc 'some-other-password 'deposit) 50)
((acc 'some-other-password 'deposit) 50)
((acc 'some-other-password 'deposit) 50)
((acc 'some-other-password 'deposit) 50)
((acc 'some-other-password 'deposit) 50)