#lang sicp

(define (front-ptr queue)
    (car queue))
(define (rear-ptr queue)
    (cdr queue))
(define (set-front-ptr! queue item)
    (set-car! queue item))
(define (set-rear-ptr! queue item)
    (set-cdr! queue item))

(define (make-queue)
    (cons '() '()))
(define (empty-queue? queue)
    (null? (front-ptr queue)))
(define (front-queue queue)
    (if (empty-queue? queue)
        (error "Empty queue" queue)
        (car (front-ptr queue))))
(define (insert-queue! queue item)
    (let ((queue-item (cons item '())))
        (if (empty-queue? queue)
            (begin
                (set-front-ptr! queue queue-item)
                (set-rear-ptr! queue queue-item)
                queue)
            (begin
                (set-cdr! (rear-ptr queue) queue-item)
                (set-rear-ptr! queue queue-item)
                queue))))
(define (delete-queue! queue)
    (if (empty-queue? queue)
        (error "Empty queue" queue)
        (begin
            (set-front-ptr! queue (cdr (front-ptr queue)))
            queue)))
(define (print-queue queue)
    (front-ptr queue))

(define (make-time-segment time queue)
    (cons time queue))
(define (segment-time s) (car s))
(define (segment-queue s) (cdr s))

(define (make-agenda) (list 0))
(define (current-time agenda) (car agenda))
(define (set-current-time! agenda time)
    (set-car! agenda time))
(define (segments agenda) (cdr agenda))
(define (set-segments! agenda segments)
    (set-cdr! agenda segments))
(define (first-segment agenda) (car (segments agenda)))
(define (rest-segments agenda) (cdr (segments agenda)))
(define (empty-agenda? agenda)
    (null? (segments agenda)))
(define (add-to-agenda! time action agenda)
    (define (belongs-before? segments)
        (or (null? segments)
            (< time (segment-time (car segments)))))
    (define (make-new-time-segment time action)
        (let ((q (make-queue)))
            (insert-queue! q action)
            (make-time-segment time q)))
    (define (add-to-segments! segments)
        (if (= (segment-time (car segments))
                time)
            (insert-queue! (segment-queue (car segments))
                action)
            (let ((rest (cdr segments)))
                (if (belongs-before? rest)
                    (set-cdr!
                        segments
                        (cons (make-new-time-segment time action)
                            (cdr segments)))
                    (add-to-segments! rest)))))
    (let ((segments (segments agenda)))
        (if (belongs-before? segments)
            (set-segments!
                agenda
                (cons (make-new-time-segment time action)
                    segments))
            (add-to-segments! segments))))
(define (remove-first-agenda-item! agenda)
    (let ((q (segment-queue (first-segment agenda))))
        (delete-queue! q)
        (if (empty-queue? q)
            (set-segments! agenda (rest-segments agenda)))))
(define (first-agenda-item agenda)
    (if (empty-agenda? agenda)
        (error "Agenda is empty: FIRST-AGENDA-ITEM")
        (let ((first-seg (first-segment agenda)))
            (set-current-time! agenda
                (segment-time first-seg))
            (front-queue (segment-queue first-seg)))))

(define the-agenda (make-agenda))

(define (after-delay delay action)
    (add-to-agenda! (+ delay (current-time the-agenda))
        action
        the-agenda))
(define (propagate)
    (if (empty-agenda? the-agenda)
        (begin (newline) 'done)
        (let ((first-item (first-agenda-item the-agenda)))
            (first-item)
            (remove-first-agenda-item! the-agenda)
            (propagate))))

(define (call-each procedures)
    (if (not (null? procedures))
        (begin
            ((car procedures))
            (call-each (cdr procedures)))))
(define (make-wire)
    (let ((signal-value 0)
            (action-procedures '()))
        (define (set-my-signal! new-value)
            (if (not (= new-value signal-value))
                (begin (set! signal-value new-value)
                    (call-each action-procedures))))
        (define (accept-action-procedure! proc)
            (set! action-procedures
                (cons proc action-procedures))
            (proc))
        (define (dispatch m)
            (cond
                ((eq? m 'get-signal) signal-value)
                ((eq? m 'set-signal!) set-my-signal!)
                ((eq? m 'add-action!) accept-action-procedure!)
                (else (error "Unknown operation: WIRE" m))))
        dispatch))

(define (get-signal wire)
    (wire 'get-signal))
(define (set-signal! wire new-value)
    ((wire 'set-signal!) new-value))
(define (add-action! wire proc)
    ((wire 'add-action!) proc))

(define (probe name wire)
    (add-action! wire
        (lambda ()
            (newline)
            (display name) (display " ")
            (display (current-time the-agenda))
            (display " New-value = ")
            (display (get-signal wire)))))

(define and-gate-delay 3)
(define or-gate-delay 5)
(define not-gate-delay 2)

(define (logical-and a b)
    (if (and (= a 1) (= b 1)) 1 0))
(define (logical-or a b)
    (if (or (= a 1) (= b 1)) 1 0))
(define (logical-not a)
    (if (= a 1) 0 1))

(define (and-gate a1 a2 output)
    (define (and-action-procedure)
        (let ((new-value
                (logical-and (get-signal a1) (get-signal a2))))
            (after-delay
                and-gate-delay
                (lambda ()
                    (set-signal! output new-value)))))
    (add-action! a1 and-action-procedure)
    (add-action! a2 and-action-procedure))
(define (or-gate o1 o2 output)
    (define (or-action-procedure)
        (let ((new-value (logical-or (get-signal o1) (get-signal o2))))
            (after-delay
                or-gate-delay
                (lambda () (set-signal! output new-value)))))
    (add-action! o1 or-action-procedure)
    (add-action! o2 or-action-procedure))
(define (not-gate n output)
    (define (not-action-procedure)
        (let ((new-value (logical-not (get-signal n))))
            (after-delay
                not-gate-delay
                (lambda () (set-signal! output new-value)))))
    (add-action! n not-action-procedure))

(define (half-adder a b s c)
    (let ((wo (make-wire))
            (wn (make-wire)))
        (and-gate a b c)
        (or-gate a b wo)
        (not-gate c wn)
        (and-gate wo wn s)))
(define (full-adder a b c-in s c-out)
    (let ((w1 (make-wire))
            (w2 (make-wire))
            (w3 (make-wire)))
        (half-adder b c-in w1 w3)
        (half-adder a w1 s w2)
        (or-gate w2 w3 c-out)))

(define (ripple-carry-adder A B S C)
    (if (null? A)
        (set-signal! C 0)
        (let ((Ai (car A))
                (Bi (car B))
                (Si (car S))
                (Ci (make-wire)))
            (full-adder Ai Bi Ci Si C)
            (ripple-carry-adder
                (cdr A)
                (cdr B)
                (cdr S)
                Ci))))

;(define a (make-wire))
;(define out (make-wire))
;(not-gate a out)
;(probe 'a a)
;(probe 'out out)
;(propagate)
;; 此时 out 应该变成 1（因为 a 初始为 0）
;; 然后改变 a 的值
;(set-signal! a 1)
;(propagate)

; (define a (make-wire))
; (define b (make-wire))
; (define out (make-wire))
; (and-gate a b out)
; (probe 'a a)
; (probe 'b b)
; (probe 'out out)
; 
; (set-signal! a 0)
; (set-signal! b 1)
; (propagate)
; (set-signal! a 1)
; (set-signal! b 1)
; (propagate)

(define A1 (make-wire))
(define A2 (make-wire))
(define A3 (make-wire))
(define B1 (make-wire))
(define B2 (make-wire))
(define B3 (make-wire))
(define S1 (make-wire))
(define S2 (make-wire))
(define S3 (make-wire))
(define C (make-wire))

(define A (list A1 A2 A3))
(define B (list B1 B2 B3))
(define S (list S1 S2 S3))
(probe 'C C)
(probe 'S1 S1)
(probe 'S2 S2)
(probe 'S3 S3)
(ripple-carry-adder A B S C)

(set-signal! A1 0)
(set-signal! A2 1)
(set-signal! A3 1)
(set-signal! B1 1)
(set-signal! B2 0)
(set-signal! B3 1)
(propagate)