#lang sicp

;a
(define (make-semaphore n)
    (let ((mutex (make-mutex)))
        (define (acquire)
            (mutex 'acquire)
            (if (> n 0)
                (begin (set! n (- n 1))
                    true)
                false)
            (mutex 'release))
        (define (release)
            (mutex 'acquire)
            (set! n (+ n 1))
            (mutex 'release))
        (define (the-semaphore m)
            (cond
                ((eq? m 'acquire) acquire)
                ((eq? m 'release) release)
                (else (error "Invalid operation: MAKE-SEMAPHORE" m))))
        the-semaphore))

;b
(define (make-semaphore n)
    (let ((cell (list false)))
        (define (acquire)
            (if (test-and-set! cell)
                (acquire)
                (let ((res (if (> n 0)
                            (set! n (- n 1))
                            false)))
                    (clear! cell)
                    res)))
        (define (release)
            (if (test-and-set! cell)
                (release)
                (set! n (+ n 1))))
        (define (the-semaphore m)
            (cond
                ((eq? m 'acquire) acquire)
                ((eq? m 'release) release)
                (else (error "Invalid operation: MAKE-SEMAPHORE" m))))
        the-semaphore))