#lang sicp

(define account-idx 0)
(define (make-account balance)
    (define (withdraw amount)
        (if (>= balance amount)
            (begin (set! balance (- balance amount))
                balance)
            "Insufficient funds"))
    (define (deposit amount)
        (set! balance (+ balance amount))
        balance)
    (let ((idx account-idx) (serializer (make-serializer)))
        (define (dispatch m)
            (cond
                ((eq? m 'withdraw) withdraw)
                ((eq? m 'deposit) deposit)
                ((eq? m 'balance) balance)
                ((eq? m 'serializer) serializer)
                ((eq? m 'idx) idx)
                (else (error "Invalid operation: MAKE-ACCOUNT" m))))
        (set! account-idx (+ idx 1))
        dispatch))

(define (serialized-exchange account1 account2)
    (let ((idx1 (account1 'idx)) (idx2 (account2 'idx)))
        (define (ordered-serialized-exchange account-low account-high)
            (let ((serializer-low (account-low 'serializer))
                    (serializer-high (account-high 'serializer)))
                ((serializer-high (serializer-low exchange))
                    account-high account-low)))
        (if (> idx1 idx2)
            (ordered-serialized-exchange account2 account1)
            (ordered-serialized-exchange account1 account2))))