#lang sicp

(define (make-account balance password)
    (define perm-error-count 0)
    (define (withdraw amount)
        (if (>= balance amount)
            (begin (set! balance (- balance amount))
                balance)
            "Insufficient funds"))
    (define (deposit amount)
        (begin (set! balance (+ balance amount))
            balance))
    (define (call-the-cops)
        "Police is comming!")
    (define (perm-error amount)
        (if (> perm-error-count 7) (call-the-cops)
            (begin (set! perm-error-count (+ perm-error-count 1))
                "Incorrect password")))
    (define (dispatch pass act)
        (cond 
            ((not (eq? pass password)) perm-error)
            ((eq? act 'withdraw) withdraw)
            ((eq? act 'deposit) deposit)
            ((eq? act 'perm-error) perm-error)
            (else (error "Unknown request: MAKE-ACCOUNT" act))))
    dispatch)

(define peter-acc (make-account 100 'open-sesame))

(define (make-joint acc password new-password)
    (define (proxy pass act)
        (if (eq? pass new-password)
            (acc password act)
            (acc password 'perm-error)))
    proxy)

(define paul-acc
    (make-joint peter-acc 'open-sesame 'rosebud))

((peter-acc 'rosebud 'withdraw) 10)
((paul-acc 'rosebud 'withdraw) 10)
((peter-acc 'open-sesame 'withdraw) 10)
((paul-acc 'open-sesame 'withdraw) 10)
((paul-acc 'open-sesame 'withdraw) 10)
((paul-acc 'open-sesame 'withdraw) 10)
((paul-acc 'open-sesame 'withdraw) 10)
((paul-acc 'open-sesame 'withdraw) 10)
((paul-acc 'open-sesame 'withdraw) 10)
((paul-acc 'open-sesame 'withdraw) 10)
((paul-acc 'open-sesame 'withdraw) 10)
((paul-acc 'open-sesame 'withdraw) 10)
((paul-acc 'open-sesame 'withdraw) 10)