#lang sicp

(define (make-leaf symbol weight)
  (list 'leaf symbol weight))
(define (leaf? object) (eq? (car object) 'leaf))
(define (symbol-leaf x) (cadr x))
(define (weight-leaf x) (caddr x))

(define (make-code-tree left right)
  (list left right
        (append (symbols left) (symbols right))
        (+ (weight left) (weight right))))
(define (left-branch tree)
  (car tree))
(define (right-branch tree)
  (cadr tree))
(define (symbols tree)
  (if (leaf? tree)
    (list (symbol-leaf tree))
    (caddr tree)))
(define (weight tree)
  (if (leaf? tree)
    (weight-leaf tree)
    (cadddr tree)))

(define (choose-branch bit branch)
  (cond ((= bit 0) (left-branch branch))
        ((= bit 1) (right-branch branch))
        (error "bad bit -- CHOOSE-BRANCH" bit)))
(define (decode bits tree)
  (define (decode-1 bits current-branch)
    (if (null? bits)
        '()
        (let ((next-branch
                (choose-branch (car bits) current-branch)))
             (if (leaf? next-branch)
                 (cons (symbol-leaf next-branch)
                       (decode-1 (cdr bits) tree))
                 (decode-1 (cdr bits) next-branch)))))
  (decode-1 bits tree))

(define sample-tree
  (make-code-tree (make-leaf 'A 4)
                  (make-code-tree
                   (make-leaf 'B 2)
                   (make-code-tree (make-leaf 'D 1)
                                   (make-leaf 'C 1)))))
(define sample-message '(0 1 1 0 0 1 0 1 0 1 1 1 0))

(define (encode message tree)
  (if (null? message)
      '()
      (cons (encode-symbol (car message) tree)
        (encode (cdr message) tree))))
(define (encode-symbol symbol tree)
  (define match-leaf 'match)
  (define nomatch-leaf 'nomatch)
  (define (encode-symbol-1 symbol current-branch)
    (if (leaf? current-branch)
        (if (eq? symbol (symbol-leaf current-branch))
            match-leaf nomatch-leaf)
        (let ((encoded-left (encode-symbol-1 symbol (left-branch current-branch))))
             (cond ((eq? encoded-left match-leaf) '(0))
                   ((not (eq? encoded-left nomatch-leaf)) (cons 0 encoded-left))
                   (else
                     (let ((encoded-right (encode-symbol-1 symbol (right-branch current-branch))))
                       (cond ((eq? encoded-right match-leaf) '(1))
                             ((not (eq? encoded-right nomatch-leaf)) (cons 1 encoded-right))
                             (else nomatch-leaf))))))))
  (let ((result (encode-symbol-1 symbol tree)))
    (if (eq? result nomatch-leaf)
        (error "Symbol not in tree -- ENCODE-SYMBOL" symbol)
        result)))

(encode (decode sample-message sample-tree) sample-tree)