#lang sicp

(define (install-variable-polynomial-package)
  (define (polynomial? x) (eq? (type-tag x) 'polynomial))
  (define (make-poly variable term-list) (cons variable term-list))
  (define (variable p) (car p))
  (define (term-list p) (cdr p))
  (define (preference? var1 var2)
    (define (preference-number var)
      (cond ((eq? var 'x) 1)
            ((eq? var 'y) 2)
            ((eq? var 'z) 3)
            (else (error "Unknown variable -- PREFERENCE?" var))))
    (> (preference-number var1) (preference-number var2)))
  (define (add-poly p1 p2)
    (let ((var1 (variable p1)) (var2 (variable p2)))
      (cond ((same-variable? var1 var2)
              (make-poly var1
                         (add-terms (term-list p1) (term-list p2))))
            ((preference? var1 var2)
              (add-poly p1 (transform-poly p2 var1)))
            (else (add-poly (transform-poly p1 var2) p2)))))
  (define (mul-poly p1 p2)
    (let ((var1 (variable p1)) (var2 (variable p2)))
      (cond ((same-variable? var1 var2)
              (make-poly var1
                         (mul-terms (term-list p1) (term-list p2))))
            ((preference? var1 var2)
              (mul-poly p1 (transform-poly p2 var1)))
            (else (mul-poly (transform-poly p1 var2) p2)))))
  (define (transform-poly p var)
    (define (sanitize-polylist poly-list)
      (define (adjoin-poly p part-list)
        (cond ((null? part-list) (cons p part-list))
              ((same-variable? (variable p) (variable (car part-list)))
                 (cons (add p (car part-list)) (cdr part-list)))
              ((same-variable? var (variable p))
                 (cons p part-list))
              (else (cons (car part-list) (adjoin-poly p (cdr part-list))))))
      (accumulate adjoin-poly '() poly-list))
    (let ((poly-list
            (map (lambda (term)
                   (let ((coefficient (coeff term))
                         (term-termlist (list (make-term 0 (make-poly (variable p) (list term))))))
                      (if (polynomial? coefficient)
                          (mul coefficient (make-poly (variable coefficient) term-termlist))
                          (make-poly var term-termlist))))
                 (term-list p))))
      (let ((sanitized-list (sanitize-polylist poly-list)))
        (accumulate add
                    (make-poly var (list (make-term 0 0)))
                    (map (lambda (poly)
                           (if (same-variable? (variable poly) var)
                               poly
                               (transform-poly poly var)))
                         sanitized-list)))))
  ;;interface to rest of the system
  (define (tag p) (attach-tag 'polynomial p))
  (put 'add '(polynomial polynomial)
    (lambda (p1 p2) (tag (add-poly p1 p2))))
  (put 'mul '(polynomial polynomial)
    (lambda (p1 p2) (tag (mul-poly p1 p2))))
  (put 'make 'polynomial
    (lambda (var terms) (tag (make-poly var terms))))
  'done)


(define (add-terms L1 L2)
  (cond ((empty-termlist? L1) L2)
        ((empty-termlist? L2) L1)
        (else
          (let ((t1 (first-term L1))
                (t2 (first-term L2)))
            (cond ((> (order t1) (order t2))
                    (adjoin-term t1 (add-terms (rest-terms L1) L2)))
                  ((< (order t1) (order t2))
                    (adjoin-term t2 (add-terms L1 (rest-terms L2))))
                  (else
                    (adjoin-term
                      (make-term (order t1)
                                 (add (coeff t1) (coeff t2)))
                      (add-terms (rest-terms L1) (rest-terms L2)))))))))
(define (mul-terms L1 L2)
  (if (empty-termlist? L1)
      (the-empty-termlist)
      (add-terms (mul-term-by-all-terms (first-term L1) L2)
                 (mul-terms (rest-terms L1) L2))))
(define (mul-term-by-all-terms t1 L)
  (if (empty-termlist? L)
      (the-empty-termlist)
      (let ((t2 (first-term L)))
        (adjoin-term
          (make-term (+ (order t1) (order t2))
                     (mul (coeff t1) (coeff t2)))
          (mul-term-by-all-terms t1 (rest-terms L))))))

(define (adjoin-term term term-list)
  (if (=zero? (coeff term))
      term-list
      (cons term term-list)))

(define (the-empty-termlist) '())
(define (first-term term-list) (car term-list))
(define (rest-terms term-list) (cdr term-list))
(define (empty-termlist? term-list) (null? term-list))

(define (make-term order coeff) (list order coeff))
(define (term-order term) (cadr term))
(define (term-coeff term) (caddr term))

(define (make-polynomial var terms)
  ((get 'make 'polynomial) var terms))